# Generated by Django 3.2.8 on 2021-11-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djfilterTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
