# Generated by Django 3.2.8 on 2021-11-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('manufacturer', models.CharField(max_length=100)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistance', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.general')),
            ],
        ),
        migrations.CreateModel(
            name='Inductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inductance', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.general')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitance', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.general')),
            ],
        ),
    ]
